name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
            */*/cjs
            */*/esm
            */*/cjs
            */*/dist
          key: ${{ runner.os }}-${ github.sha }

      - name: install deps
        run: yarn

      - name: lint
        run: yarn lint

      - name: build
        run: yarn build

      - name: test
        run: yarn test

  deploy:
    needs: build
    # if: ${{ github.event_name != 'pull_request' && contains(github.ref, 'release') }}

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master

      - name: restore cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
            */*/cjs
            */*/esm
            */*/cjs
            */*/dist
          key: ${{ runner.os }}-${ github.sha }

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/docker-login@v1
        with:
          login-server: stakessocial.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t stakessocial.azurecr.io/stakessocial:${{ github.sha }}
          docker push stakessocial.azurecr.io/stakessocial:${{ github.sha }}

      - uses: azure/webapps-container-deploy@v1
        with:
          app-name: 'stakes-social'
          images: 'stakessocial.azurecr.io/stakessocial:${{ github.sha }}'

      - name: Azure logout
        run: |
          az logout
