name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: cache build outputs
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
            */*/cjs
            */*/esm
            */*/.next
          key: ${{ runner.os }}-${ GITHUB_SHA }
            
      - name: install deps
        run: yarn

      - name: lint
        run: yarn lint

      - name: build
        run: yarn build

      - name: test
        run: yarn test

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: restore cache build outputs
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
            */*/cjs
            */*/esm
            */*/.next
          key: ${{ runner.os }}-${ GITHUB_SHA }

      - uses: haya14busa/action-cond@v1
        id: args
        with:
          cond: contains(github.ref, 'master')
          if_true: "--prod"
          if_false: ""

      - name: deploy to vercel
        uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.X_VERCEL_TOKEN }}
          github-token: ${{ secrets.X_GITHUB_TOKEN }} 
          now-args: ${{ steps.args.outputs.value }}
          now-org-id: ${{ secrets.X_VERCEL_ORG_ID}}
          now-project-id: ${{ secrets.X_VERCEL_PROJECT_ID}}
