name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install deps
        run: yarn

      - name: lint
        run: yarn lint

      - name: build
        run: yarn build
        env:
          END_POINT: ${{ secrets.END_POINT }}

      - name: test
        run: yarn test

      - name: archive artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: packages/web/out

  deploy:
    needs: build

    if: contains(github.ref, 'master')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: download artifacts
        uses: actions/download-artifact@v1
        with:
          name: build

      - uses: bacongobbler/azure-blob-storage-upload@v1.0.0
        with:
          source_dir: build
          container_name: $web
          connection_string: ${{ secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING }}
